server:
  port: 8686
management:
  security:
    enabled: false
  port: 8889 

#配置端点
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: true
    
info:
   app:
      name: spring-boot-actuator
      version: 1.0.0

#配置安全（添加一个jar），获取时必须要输入账号密码
security:
  user:
    name: zhd 
    password: 123   